apiVersion: pipeline.knative.dev/v1alpha1
kind: PipelineResource
metadata:
  name: source
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/cb-kubecd/pipeline-golang-sample