apiVersion: pipeline.knative.dev/v1alpha1
kind: Task
metadata:
  name: build-docker-image-from-git-source
spec:
  inputs:
    resources:
      - name: source
        type: git
        targetPath: go/src/github.com/cb-kubecd/pipeline-golang-sample
    params:
      - name: pathToDockerFile
        description: The path to the dockerfile to build
        default: /workspace/go/src/github.com/cb-kubecd/pipeline-golang-sample/Dockerfile
      - name: pathToContext
        description:
          The build context used by Kaniko
          (https://github.com/GoogleContainerTools/kaniko#kaniko-build-contexts)
        default:  /workspace/go/src/github.com/cb-kubecd/pipeline-golang-sample/
  outputs:
    resources:
      - name: builtImage
        type: image
  steps:
    - name: build-binary
      image: docker.io/jenkinsxio/builder-go:0.1.209
      command:
        - make
        - build
      workingDir: "/workspace/go/src/github.com/cb-kubecd/pipeline-golang-sample"
      env:
        - name: GOPATH
          value: /workspace/go
    - name: build-and-push
      image: gcr.io/kaniko-project/executor
      command:
        - /kaniko/executor
      args:
        - --dockerfile=${inputs.params.pathToDockerFile}
        - --destination=${outputs.resources.builtImage.url}
        - --context=${inputs.params.pathToContext}